// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DatepickerController from "./datepicker_controller"
application.register("datepicker", DatepickerController)

import HomeController from "./home_controller"
application.register("home", HomeController)

import ReadMoreController from "./read_more_controller"
application.register("read-more", ReadMoreController)

import RegisterTimezoneController from "./register_timezone_controller"
application.register("register-timezone", RegisterTimezoneController)

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)
